version: '3'

services:

    app:
        depends_on:
            - db
        build:
            dockerfile: ./Dockerfile
        ports:
            - "80:80"
        tty: true
        volumes:
            - .:/go/src
        container_name: app
    
    db:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db 
        container_name: db
