version: '3'

services:

    app:
        depends_on:
            - db
        build: "./app"
        ports:
            - "80:80"
        tty: true
        volumes:
            - ./app:/go/src/app
        container_name: app

    db:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db 
        container_name: db
