version: '3'

services:

    app:
        depends_on:
            - db
        build:
            dockerfile: ./Dockerfile
        ports:
            - "8080:8080"
        expose:
            - "8080"
        tty: true
        volumes:
            - .:/go/src
        container_name: app
        networks:
            - user

    db:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db 
        container_name: db
        networks:
            - user

networks:
    user:
        external: true
